encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.route, name="title"),
    path("search/", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random/", views.random_page, name="random"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
import markdown2
from . import util
from django import forms
import random

# Class inheritance from django built-in forms
class SearchForm (forms.Form):
    search = forms.CharField(label="Search Encyclopedia")

# Class for submitting New Page
class NewPageForm (forms.Form):
    page_title = forms.CharField()
    md_content = forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":20}))

# Class for Editting Pages
class EditForm (forms.Form):
    md_content = forms.CharField(label="Markdown Content", widget=forms.Textarea(attrs={"rows":5, "cols":20}))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": SearchForm()
    })

def route(request, title):

    # Obtain file from entries folder
    md = util.get_entry(title)

    if md == None:
        error = "does not exist"
        return render(request, "encyclopedia/error.html", {
            "title": title,
            "form": SearchForm(),
            "message": error
            })

    # Convert Markdown to HTML
    html = markdown2.markdown(md)

    return render(request, "encyclopedia/title.html", {
        "title": title,
        "html": html,
        "form": SearchForm()
    })



def search(request):
  
    if request.method == 'POST':

        # Get Search Entry and store in form
        form = SearchForm(request.POST)  

        # is_valid python function returning boolean expression (Ex. blank = False)
        if form.is_valid():

            # Cleaned_data used to avoid attacks, secure input
            search_entry = form.cleaned_data["search"]

            for item in util.list_entries():
                
                # If match return the HTML page
                if item.lower() == search_entry.lower():
                    md = util.get_entry(item)
                    html = markdown2.markdown(md) 
                    return render(request, "encyclopedia/title.html", {
                        "title": search_entry,
                        "html": html,
                        "form": SearchForm()
                    })

            # Encyclopedia entry does not match, Search List
            x = len(search_entry)
            matches = []
            found_match = False
            
            # Create list of matches
            for item in util.list_entries():
                if item[0:x] == search_entry:
                    matches.append(item)
                    found_match = True
                
            
            if found_match == True:
                # Pass matches list and search_entry to search.html
                return render(request, "encyclopedia/search.html", {
                        "matches": matches,
                        "form": SearchForm(),
                        "search": search_entry
                    })
            else:
                error = "does not exist"
                return render(request, "encyclopedia/error.html", {
                    "title": search_entry,
                    "form": SearchForm(),
                    "message": error
                })

    else:   
        return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": SearchForm()
    })


def create(request):

    if request.method == 'POST':

        # Get Search Entry and store in form
        form = NewPageForm(request.POST)

        # is_valid python function returning boolean expression (Ex. blank = False)
        if form.is_valid():

            # Cleaned_data used to avoid attacks, secure input
            title = form.cleaned_data["page_title"]
            md = form.cleaned_data["md_content"]

            error = "already exists"

            # For Loop if encyclopedia entry exists, return error message
            for item in util.list_entries():
                if item == title:
                    return render(request, "encyclopedia/error.html", {
                    "title": title,
                    "form": SearchForm(),
                    "message": error
                    })

            # Save Entry
            util.save_entry(title, md)

            # Convert Markdown to HTML
            html = markdown2.markdown(md)

            return render(request, "encyclopedia/title.html", {
                "title": title,
                "html": html,
                "form": SearchForm()
    })
    else:
        return render(request, "encyclopedia/create.html", {
            "entries": util.list_entries(),
            "new_page_form": NewPageForm(),
            "form": SearchForm()
    })


def edit(request, title):
    if request.method == 'POST':

        # Same sequence as Create : POST
        form = EditForm(request.POST)

        if form.is_valid():

            md = form.cleaned_data["md_content"]
            util.save_entry(title, md)
            html = markdown2.markdown(md)
            return render(request, "encyclopedia/title.html", {
                "title": title,
                "html": html,
                "form": SearchForm()
            })          


    else:
        md = util.get_entry(title)

        # Initalize form value
        content = EditForm(initial={'md_content': md}, auto_id=False)

        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "md": md,
            "form": SearchForm(),
            "content": content
        })

def random_page(request):

    # Generate random number, title
    entries = len(util.list_entries())
    n = random.randint(0, entries - 1)

    title = util.list_entries()[n]

    # Obtain HTML content
    md = util.get_entry(title)
    html = markdown2.markdown(md) 

    return render(request, "encyclopedia/title.html", {
                "title": title,
                "html": html,
                "form": SearchForm()
            })    

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>
        <form action="{% url 'wiki:create' %}" method="post">
            {% csrf_token %}
            <div class="labels">
                <h6>Page Title</h6>
                {{ new_page_form.page_title }}
            </div>
            <div class="labels">
                <h6>Markdown Content</h6>
                {{ new_page_form.md_content}}
            </div>
            <input type="submit" value="Save Entry">
        </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>Edit Page for {{ title }}</h1>

    <form action="{% url 'wiki:edit' title %}" method="post">
        {% csrf_token %}
        <div>
        {{ content.md_content }}
        </div>
        <input type="submit" value="Save Entry">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>Error</h1>

    <p>Wiki Page for {{ title }} {{ message }}.<p>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:title' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <div id ="form">
                    <div>
                        <a href="{% url 'wiki:index' %}">Home</a>
                    </div>
                    <div>
                        <a href="{% url 'wiki:create' %}">Create New Page</a>
                    </div>
                    <div>
                        <a href="{% url 'wiki:random' %}">Random Page</a>
                    </div>
                </div>
                <div id ="form">
                    <form action="{% url 'wiki:search' %}" method="post">
                        {% csrf_token %}
                        {{ form }}
                    <input id="button" type="submit">
                    </form>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Results for {{ search }}</h1>

    <ul>
        {% for item in matches %}
            <li><a href="{% url 'wiki:title' title=item %}">{{ item }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ html |safe }}

    <div>
        <a href="{% url 'wiki:edit' title %}">Edit {{ title }}.</a>
    </div>
{% endblock %}